# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMWj_Ryu3Sa0tO2zpCYhsDTNW9ig2WJN
"""

print("Campus Assistant Bot: Hello! I am your campus assistant 😊")
print("You can ask about timetable, exams, faculty, events. Type 'exit' to stop.\n")

while True:
    user = input("You: ").lower()

    if "timetable" in user:
        print("Bot: Your class timetable is available on the student portal.\n")

    elif "exam" in user:
        print("Bot: Exams are scheduled in the last week of the month.\n")

    elif "faculty" in user:
        print("Bot: Faculty details are available in the department office or website.\n")

    elif "event" in user:
        print("Bot: Upcoming event: Tech Fest next month.\n")

    elif "hello" in user or "hi" in user:
        print("Bot: Hello! How can I help you today?\n")

    elif "thank" in user:
        print("Bot: You're welcome 😊 Anything else I can help you with?\n")

    elif "bye" in user or "exit" in user:
        print("Bot: Thank you! Have a nice day 😊")
        break

    else:
        print("Bot: Sorry, I didn’t understand that. Please ask about timetable, exams, faculty, or events.\n")